[package]
name = "silo-cbr-wasm-probe"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
aidoku = { git = "https://github.com/Aidoku/aidoku-rs.git" }
wasmi = { version = "=2.0.0", default-features = false, features = ["stable", "validate", "portable-dispatch", "libm", "prefer-btree-collections"] }

[dev-dependencies]
aidoku = { git = "https://github.com/Aidoku/aidoku-rs.git", features = ["test"] }
aidoku-test = { git = "https://github.com/Aidoku/aidoku-rs.git" }

[profile.release]
panic = "abort"
opt-level = "s"
strip = true
lto = true

[profile.dev]
panic = "abort"
