//! Bounded RAR decoding through the isolated, import-free Wasm guest.
//!
//! The production source stays `no_std`; the guest is the only component that
//! links the std-enabled RAR implementation. Every invocation gets a fresh
//! Wasmi store and instance so input, output, fuel, and memory do not survive
//! across page requests.

use aidoku::{
	Result,
	alloc::{string::String, vec, vec::Vec},
	prelude::*,
};
use serde::Deserialize;
use wasmi2::{Config, Engine, Linker, Module, Store, StoreLimitsBuilder};

pub const MAX_ARCHIVE_BYTES: u64 = 16 * 1024 * 1024;
pub const MAX_PAGE_BYTES: u64 = 16 * 1024 * 1024;
pub const MAX_TOTAL_UNPACKED_BYTES: u64 = 64 * 1024 * 1024;
pub const MAX_MEMBERS: usize = 512;

const MAX_GUEST_MEMORY_BYTES: usize = 128 * 1024 * 1024;
const GUEST_FUEL: u64 = 500_000_000;
const IMAGE_EXTENSIONS: [&str; 7] = [".jpg", ".jpeg", ".png", ".webp", ".gif", ".avif", ".bmp"];

// Generated by experiments/cbr-wasm/build.sh before building this feature.
// The default and native builds do not need the guest artifact.
const GUEST_WASM: &[u8] = include_bytes!(concat!(
	env!("CARGO_MANIFEST_DIR"),
	"/../../experiments/cbr-wasm/artifacts/rar-guest.wasm"
));

#[derive(Debug, Deserialize)]
struct GuestMember {
	index: u32,
	name: String,
	size: u64,
	directory: bool,
	encrypted: bool,
	split: bool,
}

pub struct Page {
	pub index: u32,
	pub name: String,
	pub size: u64,
}

/// Lists image members after validating the guest's complete archive metadata.
pub fn list_pages(input: &[u8]) -> Result<Vec<Page>> {
	let output = call_guest(input, -1)?;
	let members: Vec<GuestMember> = serde_json::from_slice(&output)
		.map_err(|e| error!("RAR decoder returned invalid member metadata: {e:?}"))?;
	if members.len() > MAX_MEMBERS {
		bail!("RAR archive has too many members.");
	}

	let mut total = 0u64;
	let mut pages = Vec::new();
	for (position, member) in members.iter().enumerate() {
		if member.index as usize != position || member.name.is_empty() {
			bail!("RAR decoder returned unreadable member metadata.");
		}
		if member.encrypted || member.split {
			bail!("Encrypted or split RAR entries are unsupported.");
		}
		total = total
			.checked_add(member.size)
			.ok_or_else(|| error!("RAR unpacked size overflow."))?;
		if member.size > MAX_PAGE_BYTES || total > MAX_TOTAL_UNPACKED_BYTES {
			bail!("RAR archive exceeds decoder size limits.");
		}
		if !member.directory && is_image(&member.name) {
			pages.push(Page {
				index: member.index,
				name: member.name.clone(),
				size: member.size,
			});
		}
	}

	if pages.is_empty() {
		bail!("The RAR comic archive contains no readable images.");
	}
	pages.sort_by(|a, b| crate::zip::natural_cmp(&a.name, &b.name));
	Ok(pages)
}

/// Extracts one member from a full archive held by the caller.
pub fn extract_member(input: &[u8], index: u32) -> Result<Vec<u8>> {
	if index as usize >= MAX_MEMBERS {
		bail!("RAR page index is outside the member limit.");
	}
	call_guest(input, index as i32)
}

/// Validates the response before giving the complete archive to the guest and
/// validates the extracted page before returning an allocation to Aidoku.
pub fn decode_page(
	code: u16,
	data: &[u8],
	index: u64,
	total: u64,
	expected_size: u64,
) -> Result<Vec<u8>> {
	if code != 200 && code != 206 {
		bail!("RAR page request returned HTTP {code}.");
	}
	if total == 0 || total > MAX_ARCHIVE_BYTES || data.len() as u64 != total {
		bail!("RAR page response is not the complete archive.");
	}
	if index >= MAX_MEMBERS as u64 || index > i32::MAX as u64 {
		bail!("RAR page index is outside the member limit.");
	}
	if expected_size > MAX_PAGE_BYTES {
		bail!("RAR page exceeds the decoder size limit.");
	}
	let output = extract_member(data, index as u32)?;
	if output.len() as u64 != expected_size {
		bail!("RAR page size did not match its declared size.");
	}
	Ok(output)
}

fn call_guest(input: &[u8], index: i32) -> Result<Vec<u8>> {
	if input.is_empty() || input.len() as u64 > MAX_ARCHIVE_BYTES {
		bail!("RAR archive is empty or exceeds the 16 MiB limit.");
	}

	let mut config = Config::default();
	config.consume_fuel(true);
	let engine = Engine::new(&config);
	let module = Module::new(&engine, GUEST_WASM)
		.map_err(|e| error!("RAR guest validation failed: {e:?}"))?;
	if module.imports().next().is_some() {
		bail!("RAR guest unexpectedly requires imports.");
	}

	let limits = StoreLimitsBuilder::new()
		.memory_size(MAX_GUEST_MEMORY_BYTES)
		.build();
	let mut store = Store::new(&engine, limits);
	store.limiter(|limits| limits);
	store
		.set_fuel(GUEST_FUEL)
		.map_err(|e| error!("RAR guest fuel setup failed: {e:?}"))?;
	let instance = Linker::new(&engine)
		.instantiate_and_start(&mut store, &module)
		.map_err(|e| error!("RAR guest startup failed: {e:?}"))?;
	let memory = instance
		.get_memory(&store, "memory")
		.ok_or_else(|| error!("RAR guest has no exported memory."))?;
	let allocate = instance
		.get_typed_func::<u32, u32>(&store, "input_alloc")
		.map_err(|e| error!("RAR guest has no input allocator: {e:?}"))?;
	let input_len = input.len() as u32;
	let input_ptr = allocate
		.call(&mut store, input_len)
		.map_err(|e| error!("RAR guest input allocation failed: {e:?}"))?;
	let input_end = (input_ptr as u64)
		.checked_add(input_len as u64)
		.ok_or_else(|| error!("RAR guest input pointer overflow."))?;
	if input_end > memory.data_size(&store) as u64 {
		bail!("RAR guest input allocation is outside memory.");
	}
	memory
		.write(&mut store, input_ptr as usize, input)
		.map_err(|e| error!("RAR guest input write failed: {e:?}"))?;

	let run = instance
		.get_typed_func::<(u32, u32, i32), u64>(&store, "rar_call")
		.map_err(|e| error!("RAR guest has no decoder entry point: {e:?}"))?;
	let packed = run
		.call(&mut store, (input_ptr, input_len, index))
		.map_err(|e| error!("RAR guest decoding failed: {e:?}"))?;
	let output_len = packed >> 32;
	let output_ptr = (packed as u32) as u64;
	if output_len > MAX_PAGE_BYTES || output_len > usize::MAX as u64 {
		bail!("RAR guest output exceeds the 16 MiB limit.");
	}
	let output_end = output_ptr
		.checked_add(output_len)
		.ok_or_else(|| error!("RAR guest output pointer overflow."))?;
	if output_end > memory.data_size(&store) as u64 {
		bail!("RAR guest output is outside memory.");
	}
	let mut output = vec![0; output_len as usize];
	memory
		.read(&store, output_ptr as usize, &mut output)
		.map_err(|e| error!("RAR guest output read failed: {e:?}"))?;
	if output.starts_with(b"ERROR:") {
		let message = core::str::from_utf8(&output[6..]).unwrap_or("unknown decoder error");
		bail!("RAR decoder failed: {message}");
	}
	Ok(output)
}

fn is_image(name: &str) -> bool {
	if name.ends_with('/') {
		return false;
	}
	let lower = name.to_ascii_lowercase();
	if lower.contains("__macosx") || lower.contains("/._") || lower.starts_with("._") {
		return false;
	}
	let base = lower.rsplit('/').next().unwrap_or("");
	if base.is_empty() || base.starts_with('.') {
		return false;
	}
	IMAGE_EXTENSIONS
		.iter()
		.any(|extension| lower.ends_with(extension))
}
